### ISSUE TITLE
MSRC question

### ISSUE THREAD

**Issue by andypnz** [NilsRo/HotWaterRecirculatingPump#1]
Hi. Sorry to ask here, but I can't report an issue on your msrc fork...

Have you used a GPS with msrc and a RP 2040? I dont think uart_pio_begin is working in nmea.c (if I add a printf after line 59 in nmea.c it never prints...)

Any ideas appreciated :-)

**Comment by NilsRo** [comment]
> Hi. Sorry to ask here, but I can't report an issue on your msrc fork...
> 
> 
> 
> Have you used a GPS with msrc and a RP 2040? I dont think uart_pio_begin is working in nmea.c (if I add a printf after line 59 in nmea.c it never prints...)
> 
> 
> 
> Any ideas appreciated :-)
> 
> 
> 
> 

Not an expert for native programming but you should check the uart with an oscilloscope. Perhaps it is the same problem I found with the HW integration. Without the pull-up the communication is not possible and the process method is never called.

**Comment by andypnz** [comment]
Hi. Thank you.... I tried the pull ups with no luck.... Seems that with debugging on the PIO falls over - so I have added some LED's to try and figure things out.... Thanks for your suggestions......
